spring:
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/mydb
      username: root
      password: 98765432
      stat-view-servlet:
        login-password: 123456
        login-username: user
        enabled: false
      web-stat-filter:
        enabled: false
  redis:
    host: localhost
    port: 6379
    database: 3
    ssl: false
    timeout: 6000
mybatis:
  type-aliases-package: com.yang.security.model
  mapper-locations: mappers/*.xml
  configuration:
    cache-enabled: true
    multiple-result-sets-enabled: true
    aggressive-lazy-loading: true
    use-column-label: true
    use-generated-keys: false
    auto-mapping-behavior: partial
    default-executor-type: simple
    map-underscore-to-camel-case: true
    local-cache-scope: session
    jdbc-type-for-null: null

logging:
  level:
    org.springframework.security: debug